services:
  backend:
    build: ./backend
    environment:
      - PORT=4000
      - DB_PATH=/app/data/db.sqlite
      - CORS_ORIGIN=*
      # - AUTH_PIN=1234          # (сонголтоор) идэвхжүүлэх бол мөрийг задлана
      - UPLOAD_DIR=/app/data/uploads
    volumes:
      - wishlist_data:/app/data
    expose:
      - "4000"

  web:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  wishlist_data:
